### ISSUE TITLE
ERROR: undefined method `state_attrs' for Net::LDAP::Entry:Class

### ISSUE THREAD

**Issue by thoutenbos** [RiotGamesCookbooks/ldap-cookbook#2]
Do you have reporting enabled in your Chef environment?

The "current_resource" attribute in the providers is set to the Net::LDAP::Entry class. Chef expects this to be a Chef::Resource class and needs certain methods on it to exist, which are used in the reporting phase. For example the "state" and "state_attrs" methods. Currently using the providers from this cookbook generates the error in the title when used with reporting enabled.

To fix this a Chef::Resource class should probably be used to store the ldap result and compare it from there.

**Comment by awillis** [comment]
I don't have an environment where reporting is used, I believe that's an enterprise feature isn't it? I'm currently in the process of relocating, I won't have a lot of time to look into this until August or so.

**Comment by thoutenbos** [comment]
Yeah I believe it is, we do use Chef enterprise so that would make sense.

I'm still in doubt whether or not to make a pull request for the fix myself, as it would be quite an extensive one I suspect. Would you be willing to review it if I did?

Good luck with your move!
